variables:
  AWS_REGION: "eu-west-1"

stages:
  - build
  - post-build
  - deliver
  - downstream

branch-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.15
  script:
    - gradle clean build
  except:
    - master
    - develop
    - uat-drop
  artifacts:
    paths:
      - build/libs/

check-dependencies:
  stage: post-build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.15
  script:
    - check_dependencies.sh
  except:
    - uat-drop

develop-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.15
  script:
    - gradle clean build publish
  only:
    - develop
  artifacts:
    paths:
      - build/libs/

uat-drop-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.15
  script:
    - gradle clean build publish
  only:
    - uat-drop
  artifacts:
    paths:
      - build/libs/

master-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.15
  script:
    - gradle clean build publish
  only:
    - master
  artifacts:
    paths:
      - build/libs/

gconf:deliver:
  stage: deliver
  image: docker-registry-eu.mdevlab.com/mcp-gconf/gconf-deliver:v3.0
  script:
    - gconf-deliver
  only:
    - master
    - develop
    - uat-drop
  artifacts:
    paths:
      - build/deliverable/
      - build/reports/
      - build/test-results/

include:
  - project: 'tfx-clearing/environments/ci'
    file: 'deployable-builds-ci.yml'