variables:
  AWS_REGION: "eu-west-1"

stages:
  - build
  - code
  - post-build
  - deliver
  - downstream

include:
  - project: 'tfx-clearing/ci-jobs'
    file: 'build/build-and-publish.yml'
  - project: 'tfx-clearing/ci-jobs'
    file: 'build/codescan.yml'
  - project: 'tfx-clearing/ci-jobs'
    file: 'build/check-dependencies.yml'
  - project: 'tfx-clearing/ci-jobs'
    file: 'deliver/gconf-deliver.yml'
  - project: 'tfx-clearing/environments/ci'
    file: 'deployable-builds-ci.yml'
