variables:
  AWS_REGION: "eu-west-1"

stages:
  - build
  - deliver
  - downstream

build-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.20
  script:
    - gradle clean build -x check
  artifacts:
    paths:
      - build/libs/

gconf:deliver:
  image: docker-registry-eu.mdevlab.com/mcp-gconf/gconf-deliver:v3.0
  stage: deliver
  script:
    - gconf-deliver --merge-hierarchy "develop"
  artifacts:
    paths:
      - build/deliverable/
      - build/gconf.deliverable.ref

gconf:deployables-dr:
  image: docker-registry-eu.mdevlab.com/mcp-gconf/gconf-deliver:v3.0
  stage: downstream
  dependencies:
    - gconf:deliver
  script:
    - export IMAGE_DIGEST=`cat build/gconf.deliverable.ref | sed 's/^.*@//g'`
    - echo "IMAGE_DIGEST=${IMAGE_DIGEST}"
    ## dr
    - curl -g --request POST --form token=${CI_JOB_TOKEN} --form ref=master "https://git.mdevlab.com/api/v4/projects/17098/trigger/pipeline?variables[IMAGE_DIGEST]=${IMAGE_DIGEST}"