stages:
  - build
  - deliver

branch-job:
  stage: build
  image: docker-registry-eu.mdevlab.com/mcp-tfx-clearing/java-builder:v1.07
  script:
    - gradle clean build -x check
  artifacts:
    paths:
      - build/libs/

gconf:deliver:
  stage: deliver
  image: docker-registry-eu.mdevlab.com/gconf/base-builder:v1.9.15
  script:
    - gconf-deliver --merge-hierarchy "develop" --base-deliverable docker-registry-eu.mdevlab.com/mcp-tfx-clearing/base-deliverable:v1.3.1
  artifacts:
    paths:
      - build/deliverable/
      - build/reports/
      - build/test-results/